[package]
name = "tools_rust"
version = "0.1.0"
authors = ["Brendan Allan <brendonovich@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.16"
exitfailure = "0.5.1"
failure = "0.1.8"
